### ISSUE TITLE
Catenary3D space transformation not working

### ISSUE THREAD

**Issue by haykath** [FreyaHolmer/Mathfs#10]
Hey, Freya!

In the Catenary3D constructor, the space is being initialized to default after p0 and axisY are set, which is causing the transformation not to work when only the constructor is used to create the struct. I've fixed it on my local copy of the lib but thought I should let you know :)

And thanks for the awesome library!

**Comment by DeepChallengerVR** [comment]
Create a pull request?

**Comment by FreyaHolmer** [comment]
thanks! fixed it now, I think~
