### ISSUE TITLE
Format as unity package

### ISSUE THREAD

**Issue by Sacristan** [FreyaHolmer/Mathfs#2]
Hey @FreyaHolmer ! An awesome contribution! Perhaps You are open making this as a unity package ? If You do not know how - i can fork it and open as pull request :)

**Comment by chrPetry** [comment]
Oh yeah, this would be a great package!

**Comment by FreyaHolmer** [comment]
I'm considering doing this soon! Does anyone have a good up-to-date resource on how to properly set it up as a package?

would make it a lil easier~

**Comment by chrPetry** [comment]
Actually the Unity manual is not a bad start:
https://docs.unity3d.com/Manual/CustomPackages.html

Though it could be more... visually appealing.

**Comment by vanilla-plus** [comment]
I'd love this too, packages are the way of the future for Unity I think.

[openupm](https://openupm.com/) would be perfect or the almighty keijiro uses [npmjs](https://www.npmjs.com/), both of which are ready-to-go. The rest is just a bit of folder structure and publishing, I've been doing a whole lot of it lately, I'd be happy to help.

There's even a way to include optional "sample" resources like scenes and scripts that demonstrate what the package can offer. I feel like that would be a particularly awesome way to get people onboard! The layout on git should look [something like this](https://github.com/vanilla-plus/upm-dev-env/tree/develop/Packages/Vanilla%20Package%20Template).

**Comment by fight4dream** [comment]
https://docs.unity3d.com/Manual/upm-manifestPkg.html
since it already has the asmdef, we just need to have a 'package.json' and it will be at least be able to import through 'Add package by git url'

**Comment by programming2012** [comment]
Hi
    https://github.com/yasirkula/UnitySimpleGDPRConsent
    This is a simple project. This project can install by unitypackage , git url or ump.

**Comment by Lazzu** [comment]
Also please consider adding it to OpenUPM package registry: https://openupm.com/

**Comment by DeepChallengerVR** [comment]
Adding on that I would appreciate this library as a .unitypackage

**Comment by hairibar** [comment]
Thank you for making it happen, Freya!
