### ISSUE TITLE
Readme UPM

### ISSUE THREAD

**Issue by johnetc** [FreyaHolmer/Mathfs#9]
V small issue. Love the library by the way, but thought I'd mention a small issue I encountered. In the readme you specify "com.acegikmo.mathfs": "https://github.com/FreyaHolmer/Mathfs" as the entry to add to the package manifest, but for me it only works when it's "com.acegikmo.mathfs": "https://github.com/FreyaHolmer/Mathfs.git" or "com.acegikmo.mathfs": "git+https://github.com/FreyaHolmer/Mathfs"

**Comment by FreyaHolmer** [comment]
ah, thanks! fixed with [28087b4](https://github.com/FreyaHolmer/Mathfs/commit/28087b4cdd6101fb26570f53ad74f268942ab8b5)
